"""
Build a variable catalog JSONL for SciSciNet v2 AutoKD datasets.

Unlike WVS (which parses a codebook PDF), SciSciNet columns are well-defined
scientometric measures. This script generates VariableCards from hand-curated
column metadata with Science of Science domain descriptions.

Output: data/processed/sciscinet/sciscinet_variable_catalog.jsonl
"""

import json
from pathlib import Path

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "data" / "processed" / "sciscinet" / "sciscinet_variable_catalog.jsonl"

# ---------------------------------------------------------------------------
# Column definitions: var_name -> metadata
# Grouped by thematic module for the concept menu.
# ---------------------------------------------------------------------------
VARIABLE_DEFINITIONS = [
    # ===== Identifiers & Context =====
    {
        "var_name": "paperid",
        "module": "Identifiers",
        "label": "Paper ID",
        "question": "Unique identifier for the paper (OpenAlex ID)",
        "variable_kind": "identifier",
        "scale_id": "string_id",
        "semantic_summary": "unique paper identifier",
    },
    {
        "var_name": "year",
        "module": "Identifiers",
        "label": "Publication year",
        "question": "Year the paper was published",
        "variable_kind": "temporal",
        "scale_id": "numeric_year",
        "semantic_summary": "publication year of the paper",
    },
    {
        "var_name": "decade",
        "module": "Identifiers",
        "label": "Publication decade",
        "question": "Decade of publication (e.g. 1990, 2000, 2010)",
        "variable_kind": "temporal",
        "scale_id": "numeric_decade",
        "semantic_summary": "publication decade",
    },
    {
        "var_name": "doctype",
        "module": "Identifiers",
        "label": "Document type",
        "question": "Type of publication: article, book, book-chapter, dissertation, preprint, review, dataset, retraction",
        "variable_kind": "categorical",
        "scale_id": "categorical_doctype",
        "options": [
            {"code": "article", "text": "Journal article"},
            {"code": "book", "text": "Book"},
            {"code": "book-chapter", "text": "Book chapter"},
            {"code": "dissertation", "text": "Dissertation/thesis"},
            {"code": "preprint", "text": "Preprint"},
            {"code": "review", "text": "Review article"},
            {"code": "dataset", "text": "Dataset"},
            {"code": "retraction", "text": "Retraction notice"},
        ],
        "semantic_summary": "document type classification of the paper",
    },
    {
        "var_name": "primary_field_name",
        "module": "Identifiers",
        "label": "Primary field",
        "question": "Primary level-0 academic field of the paper (highest OpenAlex score)",
        "variable_kind": "categorical",
        "scale_id": "categorical_field",
        "semantic_summary": "primary academic discipline of the paper",
    },
    {
        "var_name": "paper_age",
        "module": "Identifiers",
        "label": "Paper age",
        "question": "Years since publication (2024 - year)",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "age of the paper in years since publication",
    },
    {
        "var_name": "is_retracted",
        "module": "Identifiers",
        "label": "Retraction flag",
        "question": "Whether the paper has been retracted (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is retracted",
    },

    # ===== Citation Impact =====
    {
        "var_name": "citation_count",
        "module": "Citation Impact",
        "label": "Total citation count",
        "question": "Total number of citations received by the paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "total citations received by the paper",
    },
    {
        "var_name": "cited_by_count",
        "module": "Citation Impact",
        "label": "Cited-by count",
        "question": "Number of distinct papers that cite this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of papers citing this paper",
    },
    {
        "var_name": "reference_count",
        "module": "Citation Impact",
        "label": "Reference count",
        "question": "Number of references (bibliography size) in the paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of references in the bibliography",
    },
    {
        "var_name": "C3",
        "module": "Citation Impact",
        "label": "3-year citations",
        "question": "Citation count within 3 years of publication (short-term impact)",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "short-term citation impact within 3 years of publication",
    },
    {
        "var_name": "C5",
        "module": "Citation Impact",
        "label": "5-year citations",
        "question": "Citation count within 5 years of publication (medium-term impact)",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "medium-term citation impact within 5 years of publication",
    },
    {
        "var_name": "C10",
        "module": "Citation Impact",
        "label": "10-year citations",
        "question": "Citation count within 10 years of publication (long-term impact)",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "long-term citation impact within 10 years of publication",
    },
    {
        "var_name": "log_citation_count",
        "module": "Citation Impact",
        "label": "Log citation count",
        "question": "Natural log of (1 + citation_count), normalizes skewed citation distribution",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "log-transformed total citation count",
    },
    {
        "var_name": "log_cited_by_count",
        "module": "Citation Impact",
        "label": "Log cited-by count",
        "question": "Natural log of (1 + cited_by_count)",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "log-transformed cited-by count",
    },
    {
        "var_name": "log_C3",
        "module": "Citation Impact",
        "label": "Log 3-year citations",
        "question": "Natural log of (1 + C3)",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "log-transformed 3-year citations",
    },
    {
        "var_name": "log_C5",
        "module": "Citation Impact",
        "label": "Log 5-year citations",
        "question": "Natural log of (1 + C5)",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "log-transformed 5-year citations",
    },
    {
        "var_name": "log_C10",
        "module": "Citation Impact",
        "label": "Log 10-year citations",
        "question": "Natural log of (1 + C10)",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "log-transformed 10-year citations",
    },
    {
        "var_name": "normalized_citation",
        "module": "Citation Impact",
        "label": "Normalized citation score",
        "question": "Field- and year-normalized citation count. A value of 1.0 means the paper is cited exactly as much as average for its field and year; >1 means above average.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "field-and-year normalized citation score relative to peers",
    },
    {
        "var_name": "citation_velocity",
        "module": "Citation Impact",
        "label": "Citation velocity",
        "question": "C10 divided by paper age — average citations per year (long-term pace)",
        "variable_kind": "derived_numeric",
        "scale_id": "numeric_continuous",
        "semantic_summary": "average citations per year based on 10-year window",
    },
    {
        "var_name": "is_hit_1pct",
        "module": "Citation Impact",
        "label": "Top 1% hit paper",
        "question": "Whether paper is in the top 1% most-cited in its field and year (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "top 1 percent most-cited paper in field and year",
    },
    {
        "var_name": "is_hit_5pct",
        "module": "Citation Impact",
        "label": "Top 5% hit paper",
        "question": "Whether paper is in the top 5% most-cited in its field and year",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "top 5 percent most-cited paper in field and year",
    },
    {
        "var_name": "is_hit_10pct",
        "module": "Citation Impact",
        "label": "Top 10% hit paper",
        "question": "Whether paper is in the top 10% most-cited in its field and year",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "top 10 percent most-cited paper in field and year",
    },

    # ===== Novelty & Disruption =====
    {
        "var_name": "disruption",
        "module": "Novelty and Disruption",
        "label": "Disruption index (CD index)",
        "question": "Disruption index (Funk & Owen-Smith 2017; Park et al. 2023). Ranges from -1 (consolidating: citing papers also cite this paper's references) to +1 (disruptive: citing papers do NOT cite this paper's references). Measures whether a paper disrupts or consolidates the existing knowledge stream.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "scale_summary": "-1 (consolidating) to +1 (disruptive)",
        "semantic_summary": "disruption index measuring whether a paper disrupts or consolidates prior work",
    },
    {
        "var_name": "Atyp_Median_Z",
        "module": "Novelty and Disruption",
        "label": "Atypicality median z-score",
        "question": "Median z-score of pairwise journal combination atypicality (Uzzi et al. 2013). Measures how unusual the paper's combination of cited journals is compared to random expectation. Higher values = more atypical/novel combinations.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "novelty of cited-journal combinations relative to random expectation (Uzzi atypicality)",
    },
    {
        "var_name": "Atyp_10pct_Z",
        "module": "Novelty and Disruption",
        "label": "Atypicality 10th percentile z-score",
        "question": "10th percentile z-score of pairwise journal combination atypicality. Captures the most conventional pair in the reference list (lower = at least one very conventional combination).",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "conventionality of the most typical journal pair in references",
    },
    {
        "var_name": "Atyp_Pairs",
        "module": "Novelty and Disruption",
        "label": "Atypicality pair count",
        "question": "Number of unique journal pairs used to compute atypicality scores",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of journal pairs in the atypicality calculation",
    },

    # ===== Sleeping Beauty =====
    {
        "var_name": "WSB_mu",
        "module": "Sleeping Beauty",
        "label": "Sleeping beauty awakening time (mu)",
        "question": "Expected awakening time parameter from the Wang-Song-Barabasi sleeping beauty model. Earlier mu = earlier awakening; later mu = longer dormancy before citation burst.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "sleeping beauty awakening time parameter (how long before citation burst)",
    },
    {
        "var_name": "WSB_sigma",
        "module": "Sleeping Beauty",
        "label": "Sleeping beauty sigma",
        "question": "Width parameter of the WSB model citation burst. Larger sigma = more spread-out burst.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "sleeping beauty burst width parameter",
    },
    {
        "var_name": "WSB_Cinf",
        "module": "Sleeping Beauty",
        "label": "Sleeping beauty Cinf",
        "question": "Long-run citation ceiling from the WSB model",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "sleeping beauty long-run citation potential",
    },
    {
        "var_name": "SB_B",
        "module": "Sleeping Beauty",
        "label": "Sleeping beauty B index",
        "question": "Beauty coefficient B (van Raan 2004). Higher B indicates a more pronounced sleeping beauty pattern.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "sleeping beauty beauty coefficient measuring delayed recognition",
    },
    {
        "var_name": "SB_T",
        "module": "Sleeping Beauty",
        "label": "Sleeping beauty awakening year",
        "question": "Year of awakening — the year when the citation trajectory changes from dormant to active",
        "variable_kind": "integer",
        "scale_id": "numeric_integer",
        "semantic_summary": "year of sleeping beauty awakening (delayed recognition onset)",
    },

    # ===== Team Composition =====
    {
        "var_name": "team_size",
        "module": "Team Composition",
        "label": "Team size (OpenAlex)",
        "question": "Number of authors as recorded in OpenAlex metadata (may be 0 for some older papers)",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of authors on the paper from OpenAlex metadata",
    },
    {
        "var_name": "team_size_derived",
        "module": "Team Composition",
        "label": "Team size (derived, more reliable)",
        "question": "Number of authors derived from the paper-author-affiliation table, falling back to OpenAlex team_size. More reliable than team_size for older papers.",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "reliable author count derived from affiliation records",
    },
    {
        "var_name": "num_authors",
        "module": "Team Composition",
        "label": "Number of distinct authors",
        "question": "Count of distinct author IDs linked to this paper in the paper-author-affiliation table",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of distinct authors on the paper",
    },
    {
        "var_name": "is_solo_author",
        "module": "Team Composition",
        "label": "Solo author flag",
        "question": "Whether the paper has a single author (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is solo-authored",
    },
    {
        "var_name": "institution_count",
        "module": "Team Composition",
        "label": "Institution count (OpenAlex)",
        "question": "Number of distinct institutions from OpenAlex metadata",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of institutions from OpenAlex metadata",
    },
    {
        "var_name": "num_institutions",
        "module": "Team Composition",
        "label": "Number of institutions (derived)",
        "question": "Count of distinct institution IDs from the paper-author-affiliation table",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of distinct institutions on the paper",
    },
    {
        "var_name": "num_countries",
        "module": "Team Composition",
        "label": "Number of countries",
        "question": "Count of distinct country codes across all author affiliations on this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of countries represented in author affiliations",
    },
    {
        "var_name": "is_international",
        "module": "Team Composition",
        "label": "International collaboration flag",
        "question": "Whether authors are from more than one country (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper involves international collaboration across countries",
    },
    {
        "var_name": "primary_country",
        "module": "Team Composition",
        "label": "Primary country",
        "question": "Country code of the first (alphabetically) affiliated country",
        "variable_kind": "categorical",
        "scale_id": "categorical_country",
        "semantic_summary": "primary country of author affiliations",
    },

    # ===== Author Metrics =====
    {
        "var_name": "first_author_hindex",
        "module": "Author Metrics",
        "label": "First author h-index",
        "question": "H-index of the first author at the time of data collection",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "h-index of the first (lead) author",
    },
    {
        "var_name": "first_author_productivity",
        "module": "Author Metrics",
        "label": "First author productivity",
        "question": "Total number of publications by the first author",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "total publication count of the first author",
    },
    {
        "var_name": "first_author_avg_c10",
        "module": "Author Metrics",
        "label": "First author avg C10",
        "question": "Average 10-year citation count across all papers by the first author",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "average long-term citation impact of the first author",
    },
    {
        "var_name": "first_author_gender_prob_female",
        "module": "Author Metrics",
        "label": "First author gender probability (female)",
        "question": "Probability that the first author is female, inferred from name (0=likely male, 1=likely female). Based on name-gender inference; NaN when inference is not possible.",
        "variable_kind": "continuous",
        "scale_id": "numeric_probability",
        "scale_summary": "0 (likely male) to 1 (likely female)",
        "semantic_summary": "inferred probability that the first author is female",
    },
    {
        "var_name": "last_author_hindex",
        "module": "Author Metrics",
        "label": "Last author h-index",
        "question": "H-index of the last author (typically the senior/corresponding author)",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "h-index of the last (senior) author",
    },
    {
        "var_name": "last_author_productivity",
        "module": "Author Metrics",
        "label": "Last author productivity",
        "question": "Total number of publications by the last author",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "total publication count of the last author",
    },
    {
        "var_name": "last_author_avg_c10",
        "module": "Author Metrics",
        "label": "Last author avg C10",
        "question": "Average 10-year citation count across all papers by the last author",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "average long-term citation impact of the last author",
    },
    {
        "var_name": "last_author_gender_prob_female",
        "module": "Author Metrics",
        "label": "Last author gender probability (female)",
        "question": "Probability that the last author is female, inferred from name",
        "variable_kind": "continuous",
        "scale_id": "numeric_probability",
        "scale_summary": "0 (likely male) to 1 (likely female)",
        "semantic_summary": "inferred probability that the last author is female",
    },

    # ===== Real-World Impact =====
    {
        "var_name": "patent_count",
        "module": "Real-World Impact",
        "label": "Patent citations",
        "question": "Number of patents that cite this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of patents citing this paper",
    },
    {
        "var_name": "newsfeed_count",
        "module": "Real-World Impact",
        "label": "News mentions",
        "question": "Number of news/media mentions of this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of news and media mentions",
    },
    {
        "var_name": "nct_count",
        "module": "Real-World Impact",
        "label": "Clinical trial links",
        "question": "Number of clinical trials (ClinicalTrials.gov) referencing this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of clinical trials linked to this paper",
    },
    {
        "var_name": "nih_count",
        "module": "Real-World Impact",
        "label": "NIH funding links",
        "question": "Number of NIH grants/awards linked to this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of NIH grants associated with this paper",
    },
    {
        "var_name": "nsf_count",
        "module": "Real-World Impact",
        "label": "NSF funding links",
        "question": "Number of NSF awards linked to this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of NSF awards associated with this paper",
    },
    {
        "var_name": "has_patent",
        "module": "Real-World Impact",
        "label": "Has patent citation",
        "question": "Whether at least one patent cites this paper (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is cited by any patent",
    },
    {
        "var_name": "has_news",
        "module": "Real-World Impact",
        "label": "Has news mention",
        "question": "Whether the paper has at least one media/news mention (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper has media coverage",
    },
    {
        "var_name": "has_clinical_trial",
        "module": "Real-World Impact",
        "label": "Has clinical trial link",
        "question": "Whether the paper is linked to at least one clinical trial (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is linked to a clinical trial",
    },
    {
        "var_name": "has_nih_funding",
        "module": "Real-World Impact",
        "label": "Has NIH funding",
        "question": "Whether the paper is linked to at least one NIH grant (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper has NIH funding",
    },
    {
        "var_name": "has_nsf_funding",
        "module": "Real-World Impact",
        "label": "Has NSF funding",
        "question": "Whether the paper is linked to at least one NSF award (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper has NSF funding",
    },

    # ===== Field & Interdisciplinarity =====
    {
        "var_name": "num_fields",
        "module": "Field and Interdisciplinarity",
        "label": "Number of fields",
        "question": "Total number of OpenAlex field tags assigned to this paper (all levels)",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "total number of field tags assigned to the paper",
    },
    {
        "var_name": "num_level0_fields",
        "module": "Field and Interdisciplinarity",
        "label": "Number of level-0 fields",
        "question": "Number of distinct top-level (level 0) disciplinary fields assigned to this paper. More than 1 indicates interdisciplinary work.",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of broad disciplinary fields the paper spans (interdisciplinarity indicator)",
    },
    {
        "var_name": "primary_field_score",
        "module": "Field and Interdisciplinarity",
        "label": "Primary field confidence score",
        "question": "OpenAlex classification score for the primary field assignment (0-1). Higher = more confident classification.",
        "variable_kind": "continuous",
        "scale_id": "numeric_probability",
        "semantic_summary": "confidence of primary field classification",
    },

    # ===== Open Access and Publishing =====
    {
        "var_name": "is_oa",
        "module": "Open Access and Publishing",
        "label": "Open access paper",
        "question": "Whether the paper is available as open access (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is published as open access",
    },
    {
        "var_name": "source_is_oa",
        "module": "Open Access and Publishing",
        "label": "Open access journal",
        "question": "Whether the journal/source is a fully open access venue (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the publication venue is an open access journal",
    },
    {
        "var_name": "has_license",
        "module": "Open Access and Publishing",
        "label": "Has open license",
        "question": "Whether the paper has an explicit open license (e.g. CC-BY) recorded (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper has an explicit open license",
    },

    # ===== Nobel and Prestige =====
    {
        "var_name": "has_nobel_connection",
        "module": "Real-World Impact",
        "label": "Nobel laureate connection",
        "question": "Whether the paper has a connection to a Nobel laureate — either authored by or about a laureate (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is connected to a Nobel laureate",
    },
    {
        "var_name": "nobel_connection_count",
        "module": "Real-World Impact",
        "label": "Nobel connection count",
        "question": "Number of distinct Nobel laureates connected to this paper",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of Nobel laureates connected to the paper",
    },

    # ===== PubMed =====
    {
        "var_name": "has_pmid",
        "module": "Real-World Impact",
        "label": "Has PubMed ID",
        "question": "Whether the paper is indexed in PubMed (has a PMID) (1=yes, 0=no). Indicates biomedical relevance.",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is indexed in PubMed (biomedical indicator)",
    },

    # ===== Reference Age Profile =====
    {
        "var_name": "mean_ref_age",
        "module": "Reference Age Profile",
        "label": "Mean reference age",
        "question": "Average age (in years) of cited references at time of publication. Higher values indicate the paper draws on older literature.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "average age of the paper's cited references",
    },
    {
        "var_name": "median_ref_age",
        "module": "Reference Age Profile",
        "label": "Median reference age",
        "question": "Median age (in years) of cited references. More robust to outliers than mean.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "median age of the paper's cited references",
    },
    {
        "var_name": "ref_age_std",
        "module": "Reference Age Profile",
        "label": "Reference age standard deviation",
        "question": "Standard deviation of reference ages. Higher values indicate a broader temporal range of cited works — mixing old and new knowledge.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "variability in the ages of cited references",
    },
    {
        "var_name": "ref_age_range",
        "module": "Reference Age Profile",
        "label": "Reference age range",
        "question": "Difference between the oldest and newest reference ages. Captures the temporal span of the bibliography.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "temporal span between oldest and newest cited references",
    },
    {
        "var_name": "pct_recent_refs_5yr",
        "module": "Reference Age Profile",
        "label": "Fraction of recent references (5yr)",
        "question": "Fraction of references published within 5 years of the citing paper. Higher = more current bibliography.",
        "variable_kind": "continuous",
        "scale_id": "numeric_proportion",
        "scale_summary": "0 to 1 proportion",
        "semantic_summary": "proportion of references from the last 5 years (recency of bibliography)",
    },
    {
        "var_name": "pct_old_refs_20yr",
        "module": "Reference Age Profile",
        "label": "Fraction of old references (20yr+)",
        "question": "Fraction of references published 20+ years before the citing paper. Higher = draws heavily on foundational/classic works.",
        "variable_kind": "continuous",
        "scale_id": "numeric_proportion",
        "scale_summary": "0 to 1 proportion",
        "semantic_summary": "proportion of references that are 20+ years old (reliance on classic literature)",
    },

    # ===== Level-1 Subfield Citation Impact =====
    {
        "var_name": "normalized_citation_l1",
        "module": "Citation Impact",
        "label": "Normalized citation score (subfield level)",
        "question": "Subfield-and-year-normalized citation count (level 1). A value of 1.0 means the paper is cited as much as average for its subfield and year; >1 means above average.",
        "variable_kind": "continuous",
        "scale_id": "numeric_continuous",
        "semantic_summary": "subfield-and-year normalized citation score at finer granularity than field-level",
    },
    {
        "var_name": "is_hit_1pct_l1",
        "module": "Citation Impact",
        "label": "Top 1% hit paper (subfield)",
        "question": "Whether paper is in the top 1% most-cited in its subfield and year (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "top 1 percent most-cited paper at the subfield level",
    },
    {
        "var_name": "is_hit_5pct_l1",
        "module": "Citation Impact",
        "label": "Top 5% hit paper (subfield)",
        "question": "Whether paper is in the top 5% most-cited in its subfield and year (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "top 5 percent most-cited paper at the subfield level",
    },
    {
        "var_name": "is_hit_10pct_l1",
        "module": "Citation Impact",
        "label": "Top 10% hit paper (subfield)",
        "question": "Whether paper is in the top 10% most-cited in its subfield and year (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "top 10 percent most-cited paper at the subfield level",
    },

    # ===== Institution Type (Team Composition) =====
    {
        "var_name": "has_industry_collab",
        "module": "Team Composition",
        "label": "Has industry collaboration",
        "question": "Whether at least one author is affiliated with a company/corporate institution (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper involves industry collaboration",
    },
    {
        "var_name": "has_healthcare_collab",
        "module": "Team Composition",
        "label": "Has healthcare institution",
        "question": "Whether at least one author is affiliated with a healthcare institution (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper involves a healthcare institution",
    },
    {
        "var_name": "num_affil_types",
        "module": "Team Composition",
        "label": "Number of affiliation types",
        "question": "Count of distinct institution types (education, company, healthcare, government, nonprofit, facility, archive) among the paper's authors. Higher = more diverse institutional collaboration.",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "diversity of institution types in author affiliations",
    },

    # ===== Text and Presentation =====
    {
        "var_name": "has_abstract",
        "module": "Text and Presentation",
        "label": "Has abstract",
        "question": "Whether the paper has an abstract recorded in the database (1=yes, 0=no)",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper has an abstract available",
    },
    {
        "var_name": "abstract_word_count",
        "module": "Text and Presentation",
        "label": "Abstract word count",
        "question": "Number of words in the paper's abstract. Proxy for paper complexity and depth of description.",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of words in the abstract (paper depth indicator)",
    },
    {
        "var_name": "title_word_count",
        "module": "Text and Presentation",
        "label": "Title word count",
        "question": "Number of words in the paper title. Shorter titles are associated with higher citation impact (Letchford et al. 2015).",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of words in the title (brevity indicator)",
    },
    {
        "var_name": "title_char_count",
        "module": "Text and Presentation",
        "label": "Title character count",
        "question": "Number of characters in the paper title.",
        "variable_kind": "count",
        "scale_id": "numeric_count",
        "semantic_summary": "number of characters in the title",
    },
    {
        "var_name": "title_has_question",
        "module": "Text and Presentation",
        "label": "Title contains question mark",
        "question": "Whether the title contains a question mark (1=yes, 0=no). Question titles may receive fewer citations (Jamali & Nikzad 2011).",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the title is phrased as a question",
    },
    {
        "var_name": "title_has_colon",
        "module": "Text and Presentation",
        "label": "Title contains colon",
        "question": "Whether the title contains a colon (1=yes, 0=no), indicating a 'Topic: Subtitle' structure.",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the title uses a colon-separated subtitle structure",
    },
    {
        "var_name": "is_english",
        "module": "Text and Presentation",
        "label": "English-language paper",
        "question": "Whether the paper's language is English (1=yes, 0=no).",
        "variable_kind": "binary",
        "scale_id": "binary_flag",
        "semantic_summary": "whether the paper is written in English",
    },
]


def main():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    with open(str(OUTPUT_PATH), "w", encoding="utf-8") as f:
        for defn in VARIABLE_DEFINITIONS:
            card = {
                "var_name": defn["var_name"],
                "module": defn.get("module", ""),
                "label": defn.get("label", ""),
                "question": defn.get("question", ""),
                "options": defn.get("options", []),
                "missing_codes": defn.get("missing_codes", {}),
                "section_theme": defn.get("section_theme", ""),
                "variable_kind": defn.get("variable_kind", ""),
                "battery_id": defn.get("battery_id", ""),
                "stem_template": defn.get("stem_template", ""),
                "item_text": defn.get("item_text", ""),
                "scale_id": defn.get("scale_id", ""),
                "scale_summary": defn.get("scale_summary", ""),
                "semantic_summary": defn.get("semantic_summary", ""),
            }
            f.write(json.dumps(card, ensure_ascii=False) + "\n")

    print(f"Written {len(VARIABLE_DEFINITIONS)} variable cards to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
